# TCL File Generated by Component Editor 8.1
# Sun Jun 05 17:50:07 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | CAMERA_IF "CAMERA_IF" v1.0
# | null 2011.06.05.17:50:07
# | 
# | 
# | C:/Altera_Project/DE2_CAMERA_81/ip/TERASIC_CAMERA/CAMERA_IF.v
# | 
# |    ./CAMERA_IF.v syn
# | 
# +-----------------------------------


# +-----------------------------------
# | module CAMERA_IF
# | 
set_module_property NAME CAMERA_IF
set_module_property VERSION 1.0
set_module_property GROUP ""
set_module_property DISPLAY_NAME CAMERA_IF
set_module_property TOP_LEVEL_HDL_FILE CAMERA_IF.v
set_module_property TOP_LEVEL_HDL_MODULE CAMERA_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file CAMERA_IF.v SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressSpan 16
set_interface_property s1 bridgesToMaster ""
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 minimumUninterruptedRunLength 1
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 0
set_interface_property s1 readWaitTime 0
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK s1_clock

add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_write write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_export
# | 
add_interface s1_export conduit end

add_interface_port s1_export avs_s1_export_clk export Output 1
add_interface_port s1_export avs_s1_export_address export Output 2
add_interface_port s1_export avs_s1_export_readdata export Input 32
add_interface_port s1_export avs_s1_export_read export Output 1
add_interface_port s1_export avs_s1_export_writedata export Output 32
add_interface_port s1_export avs_s1_export_write export Output 1
add_interface_port s1_export avs_s1_export_reset export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_clock
# | 
add_interface s1_clock clock end
set_interface_property s1_clock ptfSchematicName ""

add_interface_port s1_clock avs_s1_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_clock_reset
# | 
add_interface s1_clock_reset clock end
set_interface_property s1_clock_reset ptfSchematicName ""

add_interface_port s1_clock_reset avs_s1_reset reset Input 1
# | 
# +-----------------------------------
