#!/bin/sh

c:/altera/91/quartus//bin/perl/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/ptf_update.pl system_0.ptf 

c:/altera/91/quartus//bin/perl/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/mk_systembus.pl --sopc_directory=$sopc_builder --sopc_perl=c:/altera/91/quartus//bin/perl --sopc_lib_path="C:/Users/jmarple/Desktop/GitPortable/Data/home/ECE354/lab5+c:/altera/91/quartus//../ip/altera/sopc_builder_ip+c:/altera/91/quartus//../ip/altera/nios2_ip+C:/altera/91/quartus/sopc_builder/components" --target_module_name=system_0 --system_directory=C:/Users/jmarple/Desktop/GitPortable/Data/home/ECE354/lab5 --system_name=system_0 --project_name=DE2_NET.quartus --sopc_quartus_dir= $1
