obj/hello_led.o: ../hello_led.c ../my_includes.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/stdio.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stdarg.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/types.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/types.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/stdio.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/stdlib.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/stdlib.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/alloca.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/string.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/unistd.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/unistd.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/features.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_flash.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_flash_types.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_flash_dev.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/priv/alt_dev_llist.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_cache.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_flash_types.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/io.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/software/hello_led_0_syslib_0/Debug/system_description/system.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/priv/alt_legacy_irq.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/software/hello_led_0_syslib_0/Debug/system_description/system.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/priv/alt_alarm.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_timestamp.h \
  /cygdrive/c/altera/91/ip/altera/sopc_builder_ip/altera_avalon_timer/HAL/inc/altera_avalon_timer.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/software/hello_led_0_syslib_0/Debug/system_description/system.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_warning.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_stdio.h \
  ../my_types.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/software/hello_led_0_syslib_0/Debug/system_description/system.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/fcntl.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/fcntl.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/stat.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/time.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/time.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  ../debug.h ../basic_io.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/io.h \
  ../LCD.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/binary_vga_controller/inc/VGA.C \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/software/hello_led_0_syslib_0/Debug/system_description/system.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/binary_vga_controller/inc/VGA.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/ISP1362/inc/HAL4D13.C \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/software/hello_led_0_syslib_0/Debug/system_description/system.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/ISP1362/inc/BasicTyp.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/ISP1362/inc/common.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/ISP1362/inc/usb_irq.h \
  /cygdrive/c/Users/ajlucia/code/lab2_ece354_new/ISP1362/inc/HAL4D13.h \
  ../isa290.h ../reg.h ../buf_man.h ../port.h ../usb.h ../ptd.h \
  ../cheeyu.h ../cheeyu.c ../ptd.c ../usb.c ../buf_man.c ../reg.c \
  ../port.c ../packet.h ../CAMERA_NIOS2_COMMAND.h ../function.h
