# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "C:/Altera_Project/DE2_NIOS_HOST_MOUSE_VGA_D5M/DE2_NIOS_HOST_MOUSE_VGA.qpf"
project_close